In [ ]:
!pip install -q yfinance pyarrow

import pandas as pd
import yfinance as yf


# ==========================================
# 1. S&P 500
# ==========================================

sp500 = yf.download(
    "^GSPC",
    start="2000-01-01",
    end="2026-01-01",
    interval="1d",
    auto_adjust=False,
    progress=False
)

# Flatten columns if needed
if isinstance(sp500.columns, pd.MultiIndex):
    sp500.columns = sp500.columns.get_level_values(0)

sp500 = sp500.reset_index()

sp500.to_parquet(
    "sp500_2000_2025.parquet",
    engine="pyarrow",
    index=False
)


# ==========================================
# 2. CBOE VIX
# ==========================================

vix_url = "https://cdn.cboe.com/api/global/us_indices/daily_prices/VIX_History.csv"

vix = pd.read_csv(vix_url)

vix["DATE"] = pd.to_datetime(vix["DATE"])

vix = vix[
    (vix["DATE"] >= "2000-01-01") &
    (vix["DATE"] <= "2025-12-31")
].copy()

vix.to_parquet(
    "vix_2000_2025.parquet",
    engine="pyarrow",
    index=False
)


print("S&P 500 shape:", sp500.shape)
print("VIX shape:", vix.shape)

display(sp500.head())
display(vix.head())

S&P 500 shape: (6539, 7)
VIX shape: (6567, 5)

Price,Date,Adj Close,Close,High,Low,Open,Volume
0,2000-01-03,1455.219971,1455.219971,1478.000000,1438.359985,1469.250000,931800000
1,2000-01-04,1399.420044,1399.420044,1455.219971,1397.430054,1455.219971,1009000000
2,2000-01-05,1402.109985,1402.109985,1413.270020,1377.680054,1399.420044,1085500000
3,2000-01-06,1403.449951,1403.449951,1411.900024,1392.099976,1402.109985,1092300000
4,2000-01-07,1441.469971,1441.469971,1441.469971,1400.729980,1403.449951,1225200000

           DATE   OPEN   HIGH    LOW  CLOSE
2524 2000-01-03  24.36  26.15  23.98  24.21
2525 2000-01-04  24.94  27.18  24.80  27.01
2526 2000-01-05  27.98  29.00  25.85  26.41
2527 2000-01-06  26.68  26.71  24.70  25.73
2528 2000-01-07  25.14  25.17  21.72  21.72

In [ ]:
print("S&P 500 SHAPE")
print(sp500.shape)

print("\nS&P 500 COLUMNS")
print(sp500.columns.tolist())

print("\nS&P 500 DTYPES")
print(sp500.dtypes)

print("\nS&P 500 DATE RANGE")
print(sp500["Date"].min(), "to", sp500["Date"].max())

print("\nS&P 500 MISSING VALUES")
print(sp500.isna().sum())

print("\nS&P 500 DUPLICATE ROWS")
print(sp500.duplicated().sum())

print("\nS&P 500 DUPLICATE DATES")
print(sp500["Date"].duplicated().sum())

print("\nS&P 500 DESCRIPTIVE STATISTICS")
display(sp500.describe().T)

S&P 500 SHAPE
(6539, 7)

S&P 500 COLUMNS
['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume']

S&P 500 DTYPES
Price
Date         datetime64[ns]
Adj Close           float64
Close               float64
High                float64
Low                 float64
Open                float64
Volume                int64
dtype: object

S&P 500 DATE RANGE
2000-01-03 00:00:00 to 2025-12-31 00:00:00

S&P 500 MISSING VALUES
Price
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

S&P 500 DUPLICATE ROWS
0

S&P 500 DUPLICATE DATES
0

S&P 500 DESCRIPTIVE STATISTICS

,count,mean,min,25%,50%,75%,max,std
Price,,,,,,,,
Date,6539,2012-12-31 14:04:31.968190976,2000-01-03 00:00:00,2006-07-05 12:00:00,2013-01-02 00:00:00,2019-07-01 12:00:00,2025-12-31 00:00:00,NaN
Adj Close,6539.0,2268.951469,676.530029,1210.269958,1526.75,2888.074951,6932.049805,1454.14291
Close,6539.0,2268.951469,676.530029,1210.269958,1526.75,2888.074951,6932.049805,1454.14291
High,6539.0,2281.546899,695.27002,1217.205017,1533.73999,2899.484985,6945.77002,1460.545277
Low,6539.0,2254.683066,666.789978,1202.700012,1519.119995,2876.699951,6921.600098,1446.660111
Open,6539.0,2268.617579,679.280029,1210.125,1527.290039,2891.165039,6936.02002,1453.876185
Volume,6539.0,3418314009.787429,0.0,2311660000.0,3529430000.0,4260655000.0,11456230000.0,1513326882.453266

In [ ]:
print("VIX SHAPE")
print(vix.shape)

print("\nVIX COLUMNS")
print(vix.columns.tolist())

print("\nVIX DTYPES")
print(vix.dtypes)

print("\nVIX DATE RANGE")
print(vix["DATE"].min(), "to", vix["DATE"].max())

print("\nVIX MISSING VALUES")
print(vix.isna().sum())

print("\nVIX DUPLICATE ROWS")
print(vix.duplicated().sum())

print("\nVIX DUPLICATE DATES")
print(vix["DATE"].duplicated().sum())

print("\nVIX DESCRIPTIVE STATISTICS")
display(vix.describe().T)

VIX SHAPE
(6567, 5)

VIX COLUMNS
['DATE', 'OPEN', 'HIGH', 'LOW', 'CLOSE']

VIX DTYPES
DATE     datetime64[ns]
OPEN            float64
HIGH            float64
LOW             float64
CLOSE           float64
dtype: object

VIX DATE RANGE
2000-01-03 00:00:00 to 2025-12-31 00:00:00

VIX MISSING VALUES
DATE     0
OPEN     0
HIGH     0
LOW      0
CLOSE    0
dtype: int64

VIX DUPLICATE ROWS
0

VIX DUPLICATE DATES
0

VIX DESCRIPTIVE STATISTICS

,count,mean,min,25%,50%,75%,max,std
DATE,6567,2013-01-16 19:32:55.148469504,2000-01-03 00:00:00,2006-07-13 12:00:00,2013-01-22 00:00:00,2019-07-30 12:00:00,2025-12-31 00:00:00,NaN
OPEN,6567.0,19.981014,2.58,14.09,17.9,23.365,82.69,8.423175
HIGH,6567.0,20.897018,9.31,14.67,18.7,24.425,89.53,9.010225
LOW,6567.0,19.056613,8.56,13.545,17.09,22.36,72.76,7.779582
CLOSE,6567.0,19.829135,9.14,13.99,17.77,23.21,82.69,8.357228

In [ ]:
sp500_dates = set(sp500["Date"])
vix_dates = set(vix["DATE"])

only_sp500 = sorted(sp500_dates - vix_dates)
only_vix = sorted(vix_dates - sp500_dates)

print("Dates only in S&P 500:", len(only_sp500))
print(only_sp500)

print("\nDates only in VIX:", len(only_vix))
print(only_vix)

Dates only in S&P 500: 0
[]

Dates only in VIX: 28
[Timestamp('2004-06-11 00:00:00'), Timestamp('2022-05-30 00:00:00'), Timestamp('2022-06-20 00:00:00'), Timestamp('2022-07-04 00:00:00'), Timestamp('2022-09-05 00:00:00'), Timestamp('2022-11-24 00:00:00'), Timestamp('2023-01-16 00:00:00'), Timestamp('2023-02-20 00:00:00'), Timestamp('2023-05-29 00:00:00'), Timestamp('2023-06-19 00:00:00'), Timestamp('2023-07-04 00:00:00'), Timestamp('2023-09-04 00:00:00'), Timestamp('2023-11-23 00:00:00'), Timestamp('2024-01-15 00:00:00'), Timestamp('2024-02-19 00:00:00'), Timestamp('2024-05-27 00:00:00'), Timestamp('2024-06-19 00:00:00'), Timestamp('2024-07-04 00:00:00'), Timestamp('2024-09-02 00:00:00'), Timestamp('2024-11-28 00:00:00'), Timestamp('2025-01-09 00:00:00'), Timestamp('2025-01-20 00:00:00'), Timestamp('2025-02-17 00:00:00'), Timestamp('2025-05-26 00:00:00'), Timestamp('2025-06-19 00:00:00'), Timestamp('2025-07-04 00:00:00'), Timestamp('2025-09-01 00:00:00'), Timestamp('2025-11-27 00:00:00')]

In [ ]:
vix_extra = vix[vix["DATE"].isin(only_vix)].copy()

display(vix_extra)

           DATE   OPEN   HIGH    LOW  CLOSE
3639 2004-06-11  15.04  15.04  15.04  15.04
8163 2022-05-30  26.16  26.81  26.08  26.54
8178 2022-06-20  32.06  32.16  30.98  31.03
8188 2022-07-04  27.96  28.10  27.46  27.53
8233 2022-09-05  26.51  26.85  25.84  25.99
8291 2022-11-24  20.50  20.54  20.31  20.42
8326 2023-01-16  19.44  19.63  19.41  19.49
8351 2023-02-20  21.06  21.28  20.96  21.23
8420 2023-05-29  17.53  17.60  17.34  17.46
8435 2023-06-19  14.09  14.19  14.01  14.19
8446 2023-07-04  13.54  13.71  13.52  13.70
8490 2023-09-04  13.62  13.82  13.51  13.82
8548 2023-11-23  12.84  12.87  12.75  12.80
8583 2024-01-15  13.23  13.34  13.20  13.25
8608 2024-02-19  14.72  14.78  14.65  14.71
8677 2024-05-27  12.41  12.49  12.35  12.36
8694 2024-06-19  12.32  12.55  12.32  12.48
8705 2024-07-04  12.10  12.35  12.09  12.26
8747 2024-09-02  15.87  15.99  15.48  15.55
8810 2024-11-28  14.07  14.07  13.87  13.90
8838 2025-01-09  18.51  18.52  17.95  18.07
8845 2025-01-20  16.46  16.59  15.80  15.81
8865 2025-02-17  15.38  15.57  15.34  15.37
8934 2025-05-26  20.75  20.83  20.30  20.57
8952 2025-06-19  21.51  22.75  21.18  22.17
8963 2025-07-04  16.93  17.67  16.92  17.48
9004 2025-09-01  16.17  16.79  15.08  16.12
9067 2025-11-27  17.22  17.36  17.05  17.21

In [ ]:
vix_extra.describe()

,DATE,OPEN,HIGH,LOW,CLOSE
count,28,28.000000,28.000000,28.000000,28.000000
mean,2023-06-03 15:25:42.857142784,17.785714,18.008929,17.528214,17.733929
min,2004-06-11 00:00:00,12.100000,12.350000,12.090000,12.260000
25%,2023-02-11 06:00:00,13.957500,14.007500,13.782500,13.880000
50%,2024-02-01 12:00:00,16.315000,16.690000,15.640000,15.965000
75%,2025-01-11 18:00:00,20.562500,20.612500,20.302500,20.457500
max,2025-11-27 00:00:00,32.060000,32.160000,30.980000,31.030000
std,NaN,5.194581,5.264210,5.026546,5.062717

In [ ]:
market = sp500.merge(
    vix,
    left_on="Date",
    right_on="DATE",
    how="inner",
    suffixes=("_SP500", "_VIX")
)

market.shape

(6539, 12)

In [ ]:
print("Rows:", len(market))
print("Start:", market["Date"].min())
print("End:", market["Date"].max())
print("Duplicate dates:", market["Date"].duplicated().sum())
print("Missing values:", market.isna().sum().sum())

Rows: 6539
Start: 2000-01-03 00:00:00
End: 2025-12-31 00:00:00
Duplicate dates: 0
Missing values: 0

In [ ]:
market.head()

,Date,Adj Close,Close,High,Low,Open,Volume,DATE,OPEN,HIGH,LOW,CLOSE
0,2000-01-03,1455.219971,1455.219971,1478.000000,1438.359985,1469.250000,931800000,2000-01-03,24.36,26.15,23.98,24.21
1,2000-01-04,1399.420044,1399.420044,1455.219971,1397.430054,1455.219971,1009000000,2000-01-04,24.94,27.18,24.80,27.01
2,2000-01-05,1402.109985,1402.109985,1413.270020,1377.680054,1399.420044,1085500000,2000-01-05,27.98,29.00,25.85,26.41
3,2000-01-06,1403.449951,1403.449951,1411.900024,1392.099976,1402.109985,1092300000,2000-01-06,26.68,26.71,24.70,25.73
4,2000-01-07,1441.469971,1441.469971,1441.469971,1400.729980,1403.449951,1225200000,2000-01-07,25.14,25.17,21.72,21.72

In [ ]:
market.tail()

,Date,Adj Close,Close,High,Low,Open,Volume,DATE,OPEN,HIGH,LOW,CLOSE
6534,2025-12-24,6932.049805,6932.049805,6937.319824,6904.910156,6904.910156,1798270000,2025-12-24,14.09,14.16,13.38,13.47
6535,2025-12-26,6929.939941,6929.939941,6945.770020,6921.600098,6936.020020,2586550000,2025-12-26,14.12,14.29,13.52,13.60
6536,2025-12-29,6905.740234,6905.740234,6920.209961,6888.759766,6903.600098,3541750000,2025-12-29,14.69,15.08,13.99,14.20
6537,2025-12-30,6896.240234,6896.240234,6913.250000,6893.470215,6900.439941,3309930000,2025-12-30,14.43,14.62,14.04,14.33
6538,2025-12-31,6845.500000,6845.500000,6901.419922,6844.549805,6898.819824,3261830000,2025-12-31,14.77,15.17,14.38,14.95

In [ ]:
market = market.rename(columns={
    "Adj Close": "SP500_Adj_Close",
    "Close": "SP500_Close",
    "High": "SP500_High",
    "Low": "SP500_Low",
    "Open": "SP500_Open",
    "Volume": "SP500_Volume",

    "OPEN": "VIX_Open",
    "HIGH": "VIX_High",
    "LOW": "VIX_Low",
    "CLOSE": "VIX_Close"
})

In [ ]:
market = market.drop(columns="DATE")

In [ ]:
market.columns.tolist()

['Date',
 'SP500_Adj_Close',
 'SP500_Close',
 'SP500_High',
 'SP500_Low',
 'SP500_Open',
 'SP500_Volume',
 'VIX_Open',
 'VIX_High',
 'VIX_Low',
 'VIX_Close']

In [ ]:
market = market[
    [
        "Date",
        "SP500_Open",
        "SP500_High",
        "SP500_Low",
        "SP500_Close",
        "SP500_Adj_Close",
        "SP500_Volume",
        "VIX_Open",
        "VIX_High",
        "VIX_Low",
        "VIX_Close"
    ]
]

In [ ]:
market.head()

,Date,SP500_Open,SP500_High,SP500_Low,SP500_Close,SP500_Adj_Close,SP500_Volume,VIX_Open,VIX_High,VIX_Low,VIX_Close
0,2000-01-03,1469.250000,1478.000000,1438.359985,1455.219971,1455.219971,931800000,24.36,26.15,23.98,24.21
1,2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1399.420044,1009000000,24.94,27.18,24.80,27.01
2,2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1402.109985,1085500000,27.98,29.00,25.85,26.41
3,2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1403.449951,1092300000,26.68,26.71,24.70,25.73
4,2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1441.469971,1225200000,25.14,25.17,21.72,21.72

In [ ]:
market.to_parquet(
    "market_2000_2025.parquet",
    engine="pyarrow",
    index=False
)

In [ ]:
test_market = pd.read_parquet("market_2000_2025.parquet")

print(test_market.shape)
display(test_market.head())

(6539, 11)

,Date,SP500_Open,SP500_High,SP500_Low,SP500_Close,SP500_Adj_Close,SP500_Volume,VIX_Open,VIX_High,VIX_Low,VIX_Close
0,2000-01-03,1469.250000,1478.000000,1438.359985,1455.219971,1455.219971,931800000,24.36,26.15,23.98,24.21
1,2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1399.420044,1009000000,24.94,27.18,24.80,27.01
2,2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1402.109985,1085500000,27.98,29.00,25.85,26.41
3,2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1403.449951,1092300000,26.68,26.71,24.70,25.73
4,2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1441.469971,1225200000,25.14,25.17,21.72,21.72

In [ ]:
from google.colab import files

files.download("market_2000_2025.parquet")